django/blog/blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    # http://127.0.0.1:8000/blog/
    path("", views.list, name="list"),
    # http://127.0.0.1:8000/blog/post/1
    path("post/<int:post_id>/", views.detail, name="detail"),
    # http://127.0.0.1:8000/blog/post/create
    path("post/create/", views.create, name="create"),
    # http://127.0.0.1:8000/blog/post/modify/1
    path("post/modify/<int:post_id>/", views.modify, name="modify"),
    # http://127.0.0.1:8000/blog/post/delete/1
    path("post/delete/<int:post_id>/", views.delete, name="delete"),
]

# 댓글
urlpatterns += [
    # http://127.0.0.1:8000/blog/post/comment/<post_id>
    path("post/comment/<int:post_id>/", views.comment_create, name="comment_create"),
]

# 좋아요
urlpatterns += [
    # http://127.0.0.1:8000/blog/post/like/<post_id>
    path("post/like/<int:post_id>/", views.post_like, name="post_like"),
]

django/blog/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

# 파일 업로드 관련
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("common/", include("common.urls")),
    path("", RedirectView.as_view(url="blog/"), name="index"),
]

# settings.py 에 설정한것 불러오기(MEDIA_URL, MEDIA_ROOT)
# blog 프로젝트 밑에 media 폴더가 자동으로 생성되고 업로드한 이미지들이 media 폴더에 추가된다
# http://127.0.0.1:8000/media/image/python.png 경로는 이런식으로 만들어짐
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# taggit (2024-07-02)
from taggit.managers import TaggableManager


# auto_now_add : 처음 생성할때 한번만 시간이 설정
# auto_now : 생성,수정 할때마다 시간 설정
# upload_to="image" : 이미지 파일을 업로드 할수있게 해줌
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, upload_to="image")
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    # taggit (2024-07-02) 추가후 migrate 한후 admin 페이지에 Posts 추가에 들어가면 Tags: 항목이 생긴걸 확인가능
    # blog-post 테이블에는 tags 컬럼이 생성이 안되고 따로 taggit_tag, taggit_taggeditem 테이블이 새로 생성된다
    # admin 페이지에서 태그를 넣고 새글을 작성하고 SQLite 를 확인해 보면 taggit_tag 에는 키워드(중복허용X), taggit_taggeditem 에는 index 정보가 들어간다
    tags = TaggableManager()
    # 좋아요 기능 (2024-07-02)
    likes = models.ManyToManyField(User, related_name="likes", blank=True)

    # models 에서 직접 Meta 로 정렬조건을 주면
    # 리스트 추출시 작성일자를 기준으로 자동으로 내림차순으로 정렬해서 추출해준다
    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    # user, post, content, created_at, modified_at
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성일자")
    modified_at = models.DateTimeField(
        auto_now=True, null=True, blank=True, verbose_name="수정일자"
    )
    # 외래키 : Post
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return "%s - %s" % (self.id, self.user)

django/blog/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = "__all__" => 다가져오면 user 도 가져와버려서 User 필수 항목입니다. Valid 가 걸림
        # 생성할때 user 는 입력을 안하니깐 제외 시킨다
        # fields = ["title", "content", "image"]
        # 태그 추가 (2024-07-02)
        fields = ["title", "content", "image", "tags"]

django/blog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import resolve_url

# django 에서 Ajax 방식 사용하는 방법
from django.http import JsonResponse


def list(request):
    # 전체 리스트 추출(페이지 나누기 전)
    # post_list = Post.objects.all()
    # context = {"post_list": post_list}

    # 페이지 나누기 개념 추가
    post_list = Post.objects.all()

    page = request.GET.get("page", 1)

    paginator = Paginator(post_list, 5)

    page_obj = paginator.get_page(page)

    context = {"post_list": page_obj}
    return render(request, "blog/list.html", context)


def detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    # 좋아요 기능 추가 (2024-07-02)
    # 로그인 유저가 해당 게시물에 좋아요 했는지 여부 파악 (존재하면 True)
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    context = {"post": post, "is_liked": is_liked}
    return render(request, "blog/post.html", context)


@login_required(login_url="common:login")
def create(request):
    if request.method == "POST":
        # 폼에 post 로 넘어오는 내용 담기 (이미지 파일은 request.FILES 이런식으로 담아야한다)
        form = PostForm(request.POST, request.FILES)
        # 폼 유효성 검증 (forms.py 에서 유효성검증이 걸림)
        if form.is_valid():
            # 유효성 통과하면 저장 (작성자 정보를 담아서 저장)
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # 태그 저장 (2024-07-02)
            form.save_m2m()

            return redirect("blog:list")
    else:
        form = PostForm()

    return render(request, "blog/create.html", {"form": form})


@login_required(login_url="common:login")
def modify(request, post_id):
    # 수정할 글 찾기
    post = get_object_or_404(Post, id=post_id)

    if request.method == "POST":
        # instance= 사용
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("blog:detail", post.id)
    else:
        # instance= 사용
        form = PostForm(instance=post)

    # form 에는 id 가 없기 때문에 post.id 를 사용하기 위해서 "post": post 를 담아가지고 간다
    return render(request, "blog/modify.html", {"form": form, "post": post})


@login_required(login_url="common:login")
def delete(request, post_id):
    # 삭제할 글 찾기
    post = get_object_or_404(Post, id=post_id)
    post.delete()

    return redirect("blog:list")


# 댓글작성
@login_required(login_url="common:login")
def comment_create(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == "POST":
        content = request.POST.get("content").strip()

        # comment = Comment.objects.create(user=request.user, post=post, content=content)
        comment = Comment(user=request.user, post=post, content=content)
        comment.save()

        return redirect("blog:detail", post_id)

    return redirect("blog:detail", post_id)

    # if request.method == "POST":
    #     form = PostForm(request.POST)
    #     if form.is_valid():

    #         comment = form.save(commit=False)

    #         comment.post = post

    #         comment.user = request.user
    #         comment.save()

    #         return redirect(
    #             "{}#comment_{}".format(
    #                 resolve_url("board:question_detail", post_id=post_id), comment.id
    #             )
    #         )
    # else:
    #     form = PostForm()

    # context = {"post": post, "form": form}
    # return render(request, "board/comment_form.html", context)


# 좋아요 , JsonResponse() Ajax 방식 사용
@login_required(login_url="common:login")
def post_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    # 로그인 유저가 해당 게시물에 좋아요 했는지 여부
    is_liked = post.likes.filter(id=request.user.id).exists()
    # 여부 변수 선언
    is_liked_change = False

    # 좋아요를 이미 했으면 제거, 안했으면 추가
    if is_liked:
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        is_liked_change = True

    # json 타입으로 보낸다
    return JsonResponse({"likes": post.likes.count(), "is_liked": is_liked_change})

django/blog/templates/blog/create.html
{% extends "base.html" %}
{% block content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h1>새글 작성</h1>
        {% include "form_errors.html" %}
        <!--이미지 업로드시 추가 : enctype="multipart/form-data" -->
        <form action="" method="post" class="my-5" enctype="multipart/form-data">
          <!-- csrf token-->
          {% csrf_token %}
          <div class="form-group mb-3">
            <label for="title">제목</label>
            <input type="text" name="title" id="title" class="form-control" value='{{form.title.value|default_if_none:""}}'></input>
          </div>
          <div class="form-group mb-3">
            <label for="subject">내용</label>
            <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
          </div>
          <!--이미지-->
          <div class="form-group mb-3">
            <label for="image">이미지</label>
            <input type="file" name="image" id="image" class="form-control"></input>
          </div>
          <!--태그-->
          <div class="form-group mb-3">
            <label for="tags">태그</label>
            <input type="text" name="tags" id="tags" class="form-control" value='{{form.tags.value|default_if_none:""}}'></input>
            <span>( 태그는 콤마로 구분해서 입력해주세요. )</span>
          </div>
          <input type="submit" value="새글작성" class="btn btn-primary"/>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

django/blog/templates/blog/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div>
          <a href="{% url "blog:create" %}" class="btn btn-primary">새글작성</a>
        </div>
        <!-- Post preview-->
        {% for post in post_list %}
          <div class="post-preview">
            <a href="{% url "blog:detail" post.id %}">
              <h2 class="post-title">
                <!-- title-->
                {{post.title}}
              </h2>
              <h3 class="post-subtitle">
                {% comment %} 
                truncatechars:100 : django 기능, 100자 이상일경우 ... 으로 생략해서 보여준다
                {% endcomment %}
                <!-- content-->
                {{post.content|truncatechars:100}}
              </h3>
            </a>
            <p class="post-meta">
              Posted by
              <a href="#!">
                <!-- user-->
                {{post.user}}
              </a>
              <!-- created_at-->
              {{post.created_at}}
            </p>
          </div>
          <!-- Divider-->
          <hr class="my-4"/>
        {% endfor %}
        <!-- 페이지 나누기-->
        <div class="d-flex justify-content-center mb-4">
          <!-- has_previous : previous 가 있으면 보여주기-->
          {% if post_list.has_previous %}
          <a class="btn btn-primary text-uppercase" href="?page={{post_list.previous_page_number}}">◀ Previous Posts</a>
          {% endif %}

          {% comment %} <a class="btn btn-primary text-uppercase" href="#!">1 / 5</a> {% endcomment %}
          <a class="btn btn-primary text-uppercase" href="#!">{{post_list.number}} / {{post_list.paginator.num_pages}}</a>

          {% if post_list.has_next %}
          <a class="btn btn-primary text-uppercase" href="?page={{post_list.next_page_number}}">Next Posts ▶</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

django/blog/templates/blog/modify.html
{% extends "base.html" %}
{% block content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h1>수정하기</h1>
        {% include "form_errors.html" %}
        <!--이미지 업로드시 추가 : enctype="multipart/form-data" -->
        <form action="" method="post" class="my-5" enctype="multipart/form-data">
          <!-- csrf token-->
          {% csrf_token %}
          <div class="form-group mb-3">
            <label for="title">제목</label>
            <input type="text" name="title" id="title" class="form-control" value='{{form.title.value|default_if_none:""}}'></input>
          </div>
          <div class="form-group mb-3">
            <label for="subject">내용</label>
            <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
          </div>
          <!--이미지-->
          <div class="form-group mb-3">
            <label for="image">이미지</label>
          </div>

          {% if form.image.value %}
            <div class="row mb-2">
              <div class="col-auto">현재</div>
              <div class="col-auto">
                <!--폼에 들어있는 이미지 가져오기-->
                <a href="{{form.image.value.url}}">
                  <span>{{form.image.value.name}}</span>
                </a>
              </div>

              <div class="col-auto">
                <!-- django 에서 name="image-clear" id="image-clear_id" 이거를 사용하면 취소 체크여부에 따라서 이미지파일을 제거해준다 -->
                <input type="checkbox" name="image-clear" id="image-clear_id" class="form-check-input">
                <label for="image-clear_id" class="form-check-label">취소</label>
              </div>
            </div>
          {% endif %}

          <div class="form-group mb-2">
            변경
            <input type="file" name="image" id="image" class="form-control"></input>
          </div>

          <div class="form-group mb-2">
            <input type="submit" value="수정" class="btn btn-primary"/>
            <a href="{% url "blog:delete" post.id %}" class="btn btn-danger">삭제</a>
            <a href="{% url "blog:list" %}" class="btn btn-info">목록</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

django/blog/templates/blog/post.html
{% extends "base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "css/post.css" %}">
{% endblock css %}
{% block content %}
  <article class="mb-4">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="row">
            <div class="col-md-10">
              <h3 class="border-bottom pb-2">
                <!-- 제목-->
                {{post.title}}
              </h3>
            </div>
          </div>

          <div class="row">
            <div class="col-md-10">
              <h3 class="border-bottom pb-2">
                <!-- 이미지 보여주기(있으면 보여주기)-->
                <!-- .url 을 사용해야 이미지가 보인다-->
                {% if post.image %}
                  <img src="{{post.image.url}}" alt="" class="mx-auto d-block">
                {% endif %}
              </h3>
            </div>
          </div>

          <div class="row">
            <div class="col-md-10">
              <!-- 본문 보여주기-->
              {{post.content}}
              <p></p>
            </div>
          </div>

          {% include "like.html" %}

          <!-- 태그-->
          <div class="row mt-4">
            <div class="col-md-10">
              {% for tag in post.tags.all %}
                <span class="badge rounded-pill text-bg-dark">#{{tag.name}}</span>
              {% endfor %}
            </div>
          </div>

          <div class="row">
            <div class="col-md-10 my-5">
              <a href="{% url "blog:modify" post.id %}" class="btn btn-info">수정</a>
              <a href="{% url "blog:list" %}" class="btn btn-success">목록</a>
            </div>
          </div>

          <!-- 댓글 목록 : .count 가 있으면 보여주기 -->
           {% if post.comment_set.count > 0 %}
          <div class="row mt-5">
            <div class="col-md-10">
              <div class="card mb-5">
                <div class="card-header">
                  <i class="fa-regular fa-comments"></i>
                  Comments
                </div>
                <!-- 댓글 for 반복-->
                {% for comment in post.comment_set.all %}
                  <div class="card-body">
                    <h5 class="card-title">
                      <!-- 댓글 내용-->
                      {{comment.content}}
                    </h5>
                    <div class="card-text text-end fs-6 bg-light">
                      <!-- 댓글 작성자 (댓글 작성일자)-->
                      {{comment.user}}
                      ({{comment.created_at}})
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
          {% endif %}

          <!-- 댓글 등록 : 로그인한 유저만 등록 보여주기 -->
           {% if user.is_authenticated %}
          {% comment %} {% include "form_errors.html" %} {% endcomment %}
          <div class="row mt-5">
            <div class="col-md-10">
              <form action="{% url "blog:comment_create" post.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <textarea name="content" id="content" class="form-control" rows="7">{{form.content.value|default_if_none:""}}</textarea>
                </div>
                <div class="form-group d-grid">
                  <button type="submit" class="btn btn-secondary">댓글등록</button>
                </div>
              </form>
            </div>
          </div>
          {% endif %}
          
        </div>
      </div>
    </div>
  </article>
{% endblock content %}
{% block script %}
  <script src="{% static "js/post.js" %}"></script>
{% endblock script %}