django/board/board/urls.py
from django.urls import path

# from . import views
# views 폴더 만들어서 views 별로 나눴음
from .views import base_views, question_views, answer_views, comment_views, vote_views

# 앱이름 (임의로 부여가능), 앱이 여러개가 들어올 경우, 각앱마다 동일한 name= 을 사용하면 다른걸 찾아올수 있어서 문제가 생길수있다
# 이러한 문제를 방지 하기위해서 앱이름도 추가하면 동일한 name= 을 문제없이 사용할수있다
# "{% url "board:question_detail" qid=question.id %}" 형태로 사용
app_name = "board"

urlpatterns = [
    # http://127.0.0.1:8000/board/
    path("", base_views.question_list, name="question_list"),
    # http://127.0.0.1:8000/board/1
    path("<int:qid>/", base_views.question_detail, name="question_detail"),
    # http://127.0.0.1:8000/board/answer/create/2 (뒤에 붙는 번호는 question_detail이 가지고 있는 질문번호)
    path("answer/create/<int:qid>/", answer_views.answer_create, name="answer_create"),
    # http://127.0.0.1:8000/board/question/create/
    path("question/create/", question_views.question_create, name="question_create"),
    # http://127.0.0.1:8000/board/question/modify/1
    path(
        "question/modify/<int:qid>",
        question_views.question_modify,
        name="question_modify",
    ),
    # http://127.0.0.1:8000/board/question/delete/1
    path(
        "question/delete/<int:qid>",
        question_views.question_delete,
        name="question_delete",
    ),
    # 답변 이라서 답변 id 를 찾아야 해서 <int:aid> 를 사용
    # http://127.0.0.1:8000/board/answer/modify/1
    path("answer/modify/<int:aid>", answer_views.answer_modify, name="answer_modify"),
    # http://127.0.0.1:8000/board/answer/delete/1
    path("answer/delete/<int:aid>", answer_views.answer_delete, name="answer_delete"),
    # 댓글(질문), <int:cid> 를 사용
    # http://127.0.0.1:8000/board/comment/create/question/1
    path(
        "comment/create/question/<int:qid>",
        comment_views.comment_create_question,
        name="comment_create_question",
    ),
    # http://127.0.0.1:8000/board/comment/modify/question/1
    path(
        "comment/modify/question/<int:cid>",
        comment_views.comment_modify_question,
        name="comment_modify_question",
    ),
    # http://127.0.0.1:8000/board/comment/delete/question/1
    path(
        "comment/delete/question/<int:cid>",
        comment_views.comment_delete_question,
        name="comment_delete_question",
    ),
    # 댓글(답변)
    # http://127.0.0.1:8000/board/comment/create/answer/1
    path(
        "comment/create/answer/<int:aid>",
        comment_views.comment_create_answer,
        name="comment_create_answer",
    ),
    # http://127.0.0.1:8000/board/comment/modify/answer/1
    path(
        "comment/modify/answer/<int:cid>",
        comment_views.comment_modify_answer,
        name="comment_modify_answer",
    ),
    # http://127.0.0.1:8000/board/comment/delete/answer/1
    path(
        "comment/delete/answer/<int:cid>",
        comment_views.comment_delete_answer,
        name="comment_delete_answer",
    ),
    # 추천 시스템
    # http://127.0.0.1:8000/board/vote/question/1 <question id> : 질문 추천
    path("vote/question/<int:qid>/", vote_views.vote_question, name="vote_question"),
    # http://127.0.0.1:8000/board/vote/answer/1 <answer id> : 답변 추천
    path("vote/answer/<int:aid>/", vote_views.vote_answer, name="vote_answer"),
]

django/board/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    # http://127.0.0.1:8000/ 를 치고 들어가도 http://127.0.0.1:8000/board 로 가게됨
    path("", RedirectView.as_view(url="/board/"), name="index"),
]

django/board/board/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect
from board.models import Question, Answer
from board.forms import QuestionForm, AnswerForm

# 권한 설정 (2024-06-28)
from django.contrib.auth.decorators import login_required

# django 가 제공하는 시간 설정 (2024-06-28)
from django.utils import timezone

# a 태그 name 활용 (2024-06-28)
from django.shortcuts import resolve_url


# 답변등록
@login_required(login_url="common:login")
def answer_create(request, qid):
    # 생성하는 방법이 여러가지가 있다

    # 2) 모델폼을 이용하는 방법
    question = get_object_or_404(Question, id=qid)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            # commit=False : 일단 DB 에 반영 하지 마시오
            answer = form.save(commit=False)
            # answer 에 question 을 담고 commit
            answer.question = question

            # 작성자 개념 추가 (2024-06-28)
            answer.author = request.user
            answer.save()
            # return redirect("board:question_detail", qid=qid)
            # detail 페이지의 특정 위치 로 이동하기 (a 태그 name 활용)
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("board:question_detail", qid=qid), answer.id
                )
            )
    else:
        form = QuestionForm()

    # 실패 시 get 방식으로 처리 해야해서 render() 를 사용
    # 실패하고 다시 detail 페이지로 돌아올때 Question내용 + form 을 가지고 다시 돌아와야한다
    context = {"question": question, "form": form}
    return render(request, "board/question_detail.html", context)

    # 1) 모델을 직접 사용하는 방법
    # - 먼저 Question 을 찾는다
    # question = get_object_or_404(Question, id=qid)
    # - 1번 방법
    # answer = Answer.objects.create(
    #     question=question, content=request.POST.get("content")
    # )
    # - 2번 방법
    # question.answer_set.create(content=request.POST.get("content"))
    # - 3번 방법
    # answer = Answer(question=question, content=request.POST.get("content"))
    # answer.save()
    # - 앱이름 사용했기 때문에 board: 를 붙여준다
    # return redirect("board:question_detail", qid=qid)


# 답변 수정
@login_required(login_url="common:login")
def answer_modify(request, aid):
    # aid 에 해당하는 답변을 찾는다
    answer = get_object_or_404(Answer, id=aid)
    # Answer 가 question 을 가지고 있어서 .찍고 접근이 가능하다
    # question_detail 로 들어갈때는 qid 가 필요함
    qid = answer.question.id

    # 변경할 부분 수정 후 save()
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)

        if form.is_valid():
            answer = form.save(commit=False)
            answer.modified_at = timezone.now()
            answer.save()
            # return redirect("board:question_detail", qid=qid)
            # detail 페이지의 특정 위치 로 이동하기 (a 태그 name 활용)
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("board:question_detail", qid=qid), answer.id
                )
            )
    else:
        form = AnswerForm(instance=answer)

    return render(request, "board/answer_form.html", {"form": form})


# 답변 삭제
@login_required(login_url="common:login")
def answer_delete(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    answer.delete()

    # Answer 가 question 을 가지고 있어서 .찍고 접근이 가능하다
    qid = answer.question.id
    return redirect("board:question_detail", qid=qid)

django/board/board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from board.models import Question

# 페이지 나누기 (Paginator, Page 클래스를 잘 활용하면 된다)
# https://docs.djangoproject.com/en/5.0/ref/paginator/ 참고
from django.core.paginator import Paginator

# Q 함수 (검색filter 조건 주기위함 , or 조건으로 데이터 조회 2024-07-01)
# Count 함수 : 정렬할때 추천수 세야해서
from django.db.models import Q, Count

# 클라이언트 ip 가져오기 (2024-07-01)
from tools.utils import get_client_ip

from board.models import QuestionCount


def question_list(request):
    # 전체 질문 추출(페이지나누기적용O, 검색기능적용X)
    # question_list = Question.objects.all()
    # question_list = Question.objects.order_by("-created_at")

    # 1. 페이지 나누기 적용
    # 1) 현재 페이지 번호 가져오기
    # => 'page',1 : 변수명은 page 로정하고 page 정보가 없으면 1 값을 적용한다
    # page = request.GET.get("page", 1)
    # 2) 리스트를 한페이지에 20개 씩 보여주기
    # paginator = Paginator(question_list, 20)
    # 3) 현재페이지에 데이터 담기?
    # page_obj = paginator.get_page(page)

    # context = {"question_list": question_list}
    # 4) 페이지 나누기 적용 후 보내기
    # context = {"question_list": page_obj}
    # return render(request, "board/question_list.html", context)

    # 2. 검색 기능 적용
    # question_list = Question.objects.order_by("-created_at")
    # page = request.GET.get("page", 1)
    # 검색어 가져오기 (검색기능 추가 2024-07-01)
    # keyword = request.GET.get("keyword", "")

    # 검색 키워드 설정 : 제목,내용,질문작성자,답변작성자
    # if keyword:
    # Question.objects.filter(Q(subject__icontains==keyword)|
    #     question_list = question_list.filter(
    #         Q(subject__icontains=keyword)
    #         | Q(content__icontains=keyword)
    #         | Q(author__username__icontains=keyword)
    #         | Q(answer__author__username__icontains=keyword)
    #     ).distinct()

    # paginator = Paginator(question_list, 20)

    # page_obj = paginator.get_page(page)

    # 검색데이터 + 정렬기준데이터 도 같이 보내기
    # context = {"question_list": page_obj, "page": page, "keyword": keyword}
    # return render(request, "board/question_list.html", context)

    # 3. 정렬 기능
    page = request.GET.get("page", 1)
    keyword = request.GET.get("keyword", "")

    # 정렬 기준 가져오기 (2024-07-01)
    so = request.GET.get("so", "")

    if so == "recommend":  # 추천 개수
        # annotate() : Question 테이블에 추천수 세서 num_voter 라는 컬럼명을 알아서 붙여서 해줘
        question_list = Question.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-created_at"
        )
    elif so == "popular":  # 답변 개수
        question_list = Question.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-created_at"
        )
    else:
        question_list = Question.objects.order_by("-created_at")

    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(author__username__icontains=keyword)
            | Q(answer__author__username__icontains=keyword)
        ).distinct()

    paginator = Paginator(question_list, 20)

    page_obj = paginator.get_page(page)

    # 검색데이터 + 정렬기준데이터 도 같이 보내기
    context = {"question_list": page_obj, "page": page, "keyword": keyword, "so": so}
    return render(request, "board/question_list.html", context)


def question_detail(request, qid):
    question = get_object_or_404(Question, id=qid)

    # 클라이언트 ip 가져오기 (2024-07-01)
    # 같은 ip 일경우 1번만 조회수 올라감
    ip = get_client_ip(request)
    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()
    if cnt == 0:
        # QuestionCount 객체 생성후 저장
        questionCount = QuestionCount(ip=ip, question=question)
        questionCount.save()
        # Question 객체에 view_cnt + 1 하기
        if question.view_cnt:
            question.view_cnt += 1
        else:
            question.view_cnt = 1
        question.save()

    # 페이지 정보 보내주기 (2024-07-01)
    page = request.GET.get("page", 1)
    keyword = request.GET.get("keyword", "")
    so = request.GET.get("so", "recent")

    # 페이지 정보 보내주기 (2024-07-01)
    context = {"question": question, "page": page, "keyword": keyword, "so": so}
    return render(request, "board/question_detail.html", context)

django/board/board/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect
from board.models import Question, Answer, Comment
from board.forms import CommentForm

# 권한 설정 (2024-06-28)
from django.contrib.auth.decorators import login_required

# django 가 제공하는 시간 설정 (2024-06-28)
from django.utils import timezone

# a 태그 name 활용 (2024-06-28)
from django.shortcuts import resolve_url


# 댓글(질문) 생성
@login_required(login_url="common:login")
def comment_create_question(request, qid):
    question = get_object_or_404(Question, id=qid)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            # commit=False : 일단 DB 에 반영 하지 마시오
            comment = form.save(commit=False)
            # comment 에 question 을 담고 commit
            comment.question = question

            # 작성자 개념 추가 (2024-06-28)
            comment.author = request.user
            comment.save()
            # return redirect("board:question_detail", qid=qid)
            # detail 페이지의 특정 위치 로 이동하기 (a 태그 name 활용)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:question_detail", qid=qid), comment.id
                )
            )
    else:
        form = CommentForm()

    # 실패 시 get 방식으로 처리 해야해서 render() 를 사용
    # 실패하고 다시 detail 페이지로 돌아올때 Question내용 + form 을 가지고 다시 돌아와야한다
    context = {"question": question, "form": form}
    return render(request, "board/comment_form.html", context)


# 댓글(질문) 수정
@login_required(login_url="common:login")
def comment_modify_question(request, cid):
    # aid 에 해당하는 답변을 찾는다
    comment = get_object_or_404(Comment, id=cid)
    # Comment 가 question 을 가지고 있어서 .찍고 접근이 가능하다
    # question_detail 로 들어갈때는 qid 가 필요함
    qid = comment.question.id

    # 변경할 부분 수정 후 save()
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.modified_at = timezone.now()
            comment.save()
            # return redirect("board:question_detail", qid=qid)
            # detail 페이지의 특정 위치 로 이동하기 (a 태그 name 활용)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:question_detail", qid=qid), comment.id
                )
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html", {"form": form})


# 댓글(질문) 삭제
@login_required(login_url="common:login")
def comment_delete_question(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    comment.delete()

    # Comment 가 question 을 가지고 있어서 .찍고 접근이 가능하다
    qid = comment.question.id
    return redirect("board:question_detail", qid=qid)


# 댓글(답변) 생성
@login_required(login_url="common:login")
def comment_create_answer(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            # comment 에 question 을 담고 commit
            comment.answer = answer

            # 작성자 개념 추가 (2024-06-28)
            comment.author = request.user
            comment.save()
            # return redirect("board:question_detail", qid=answer.question.id)
            # detail 페이지의 특정 위치 로 이동하기 (a 태그 name 활용)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:question_detail", qid=answer.question.id),
                    comment.id,
                )
            )
    else:
        form = CommentForm()

    return render(request, "board/comment_form.html", {"form": form})


# 댓글(답변) 수정
@login_required(login_url="common:login")
def comment_modify_answer(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    # comment_create_answer 가 aid 를 가지고 와서 comment.question.id 는 null 이다 그래서 answer 를 한번 더 들어가야한다
    qid = comment.answer.question.id

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.modified_at = timezone.now()
            comment.save()
            # return redirect("board:question_detail", qid=qid)
            # detail 페이지의 특정 위치 로 이동하기 (a 태그 name 활용)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:question_detail", qid=qid), comment.id
                )
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html", {"form": form})


# 댓글(답변) 삭제
@login_required(login_url="common:login")
def comment_delete_answer(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    comment.delete()

    qid = comment.answer.question.id
    return redirect("board:question_detail", qid=qid)

django/board/board/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from board.models import Question
from board.forms import QuestionForm

# 권한 설정 (2024-06-28)
from django.contrib.auth.decorators import login_required

# django 가 제공하는 시간 설정 (2024-06-28)
from django.utils import timezone


# @login_required : 권한설정,로그인한 유저만 작성가능(2024-06-28)
# (login_url="common:login") : 권한이 없으면 로그인 페이지로 보낸다
@login_required(login_url="common:login")
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            # form.save()

            # 작성자 = 로그인유저 개념 추가 (2024-06-28)
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            return redirect("board:question_list")
    else:
        form = QuestionForm()
    return render(request, "board/question_form.html", {"form": form})


# 질문수정
@login_required(login_url="common:login")
def question_modify(request, qid):
    # qid 에 해당하는 질문을 찾는다
    question = get_object_or_404(Question, id=qid)

    # 변경할 부분 수정 후 save()
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)

        if form.is_valid():
            question = form.save(commit=False)
            question.modified_at = timezone.now()
            question.save()
            return redirect("board:question_detail", qid=qid)
    else:
        form = QuestionForm(instance=question)

    return render(request, "board/question_form.html", {"form": form})


# 질문삭제
@login_required(login_url="common:login")
def question_delete(request, qid):
    # qid 에 해당하는 질문을 찾는다
    question = get_object_or_404(Question, id=qid)

    question.delete()
    return redirect("board:question_list")

django/board/templates/board/answer_form.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h5 class="my-3 border-bottom pb-2">답변 수정</h5>
    {% comment %} 
    여기는 GET 과 POST 주소가 동일해서 action 을 안준다
    {% endcomment %}
    <form action="" method="post" class="my-3">
    {% include "form_errors.html" %}
      <!-- csrf token-->
      {% csrf_token %}
      <!-- 오류 표시 영역-->
      <div class="form-group mb-3">
        <label for="subject">내용</label>
        <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
      </div>
      <input type="submit" value="답변 수정" class="btn btn-primary"/>
    </form>
  </div>
{% endblock content %}

django/board/templates/board/question_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container mt-5">
    {% comment %} 
    메세지 띄우는 방법
    board/views.py 에서 def vote_question(request, qid): messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")

    if messages : messages 가 있으면 보여주기
    {% endcomment %}
    {% if messages %}
    <div class="alert alert-danger">
      {% for msg in messages %}
            <strong>{{ msg.tags }}</strong>
            <ul>
              <li>{{msg.message}}</li>
            </ul>
      {% endfor %} 
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">
      <!-- 질문제목-->
      {{question.subject}}
    </h2>
    <!-- 추천 영역-->
    <div class="row my-3">
      <div class="col-1">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
          <!--추천수-->
          {{question.voter.count}}
        </div>
        <div class="d-grid d-block">
          <a href="{% url "board:vote_question" question.id %}" class="recommand btn btn-sm btn-secondary">추천</a>
        </div>
      </div>
      <div class="col-11">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <!--질문내용-->
              {{question.content}}
            </div>
            <div class="d-flex justify-content-end">
              {% if question.modified_at %}
                <div class="badge text-bg-light p-2 text-start">
                  <div class="mb-2">modified at</div>
                  <div>
                    <!--질문 수정 날짜-->
                    {{question.modified_at}}
                  </div>
                </div>
              {% endif %}
              <div class="badge text-bg-light p-2 text-start">
                <div class="mb-2">
                  <!--작성자(2024-06-28)-->
                  {{question.author}}
                </div>
                <div>
                  <!--질문 작성 날짜-->
                  {{question.created_at}}
                </div>
              </div>
            </div>
            {% comment %} 작성자 == 로그인 사용자 일경우에만 수정/삭제 버튼 보여주기 {% endcomment %}
            {% if question.author == request.user %}
            <div class="my-3">
              <a href="{% url "board:question_modify" question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
              <a href="{% url "board:question_delete" question.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>
            <!--// 질문 영역 종료-->
            {% endif %}

            <!-- 질문 댓글 영역-->
             {% comment %} 
             Comment 가 question 을 가지고 있고 Question 은 comment 가 없는 상황에서
             Question 에서 Comment 로 역으로 접근하는 방법 : _set 을 사용한다
             question.comment_set.count > 0 : 댓글이 있으면 댓글영역 보여주기
             {% endcomment %}
             {% if question.comment_set.count > 0 %}
            <div class="mt-3">
              {% for comment in question.comment_set.all %}
              {% comment %} 질문댓글 a 태그의 name 속성 활용 {% endcomment %}
              <a name="comment_{{comment.id}}"></a>
              <div class="comment py-2 text-muted">
                <span style="white-space: pre-line">{{comment.content}}</span>
                <span>
                  <!--댓글 작성자 / 작성일시 / 수정일시-->
                  - {{comment.author}}, {{comment.created_at}}
                  {% if comment.modified_at %}
                  (수정 : {{comment.modified_at}})
                  {% endif %}
                </span>
                <a href="{% url "board:comment_modify_question" comment.id %}" class="small">수정</a>
                <a href="{% url "board:comment_delete_question" comment.id %}" class="small delete">삭제</a>
              </div>
              {% endfor %}
            </div>
            {% endif %}
          </div>
          <div class="mx-3">
            <a href="{% url "board:comment_create_question" question.id %}" class="small">댓글추가....</a>
          </div>
        </div>
      </div>
    </div>

    <h5 class="border-bottom my-3 py-2">
      <!--답변 개수-->
      {% comment %}
      django 에서 사용하는 Question -> Answer 로 접근 방법 (1->N 접근)
      question.answer_set
      스프링부트 에서는 1->N 접근 하려면 코드를 더 추가해야 하는데 django 에서는 _set 을 사용하면 간단하게 접근가능
      {% endcomment %}
      {{question.answer_set.count}} 개의 답변이 있습니다.
    </h5>

    {% comment %} html 에서는 all 에서 괄호는 빼고 부른다 {% endcomment %}
    {% for answer in question.answer_set.all %}
    {% comment %} a 태그의 name 속성 활용 {% endcomment %}
    <a name="answer_{{answer.id}}"></a>
    <div class="row my-3">
      {% comment %} 답변 추천 {% endcomment %}
      <div class="col-1">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
          {{answer.voter.count}}
        </div>
        <div class="d-grid d-block">
          <a href="{% url "board:vote_answer" answer.id %}" class="recommand btn btn-sm btn-secondary">추천</a>
        </div>
      </div>
      <div class="col-11">
        
        <div class="card">
          <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
              <!--답변내용-->
              {{answer.content}}
            </div>
            <div class="d-flex justify-content-end">
              {% if answer.modified_at %}
              <div class="badge text-bg-light p-2 text-start">
                <div class="mb-2">modified_at</div>
                <div>
                  <!--답변수정날짜-->
                  {{answer.modified_at}}
                </div>
              </div>
              {% endif %}

              <div class="badge text-bg-light p-2 text-start">
                <div class="mb-2">
                  <!--답변 작성자(2024-06-28)-->
                  {{answer.author}}
                </div>
                <div>
                  <!--답변작성날짜-->
                  {{answer.created_at}}
                </div>
              </div>
            </div>
            {% comment %} 작성자 == 로그인 사용자 일경우에만 수정/삭제 버튼 보여주기 {% endcomment %}
            {% if answer.author == request.user %}
            <div class="my-3">
              <a href="{% url "board:answer_modify" answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
              <a href="{% url "board:answer_delete" answer.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>
            {% endif %}
          </div>
          <!--// 답변 종료-->

          <!-- 답변 댓글 영역-->
          {% if answer.comment_set.count > 0 %}
          <div class="mt-3">
            {% for comment in answer.comment_set.all %}
            {% comment %} 답변댓글 a 태그의 name 속성 활용 {% endcomment %}
            <a name="comment_{{comment.id}}"></a>
            <div class="comment py-2 text-muted">
              <span style="white-space: pre-line">{{comment.content}}</span>
              <span>
                <!--댓글 작성자 / 작성일시 / 수정일시-->
                - {{comment.author}}, {{comment.created_at}}
                  {% if comment.modified_at %}
                  (수정 : {{comment.modified_at}})
                  {% endif %}
              </span>
              <a href="{% url "board:comment_modify_answer" comment.id %}" class="small">수정</a>
              <a href="{% url "board:comment_delete_answer" comment.id %}" class="small delete">삭제</a>
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <a href="{% url "board:comment_create_answer" answer.id %}" class="small">
            <small>댓글추가...</small>
          </a>
        </div>
        <div>
        </div>
        <!--//질문 댓글 end-->
      </div>
    </div>
    {% endfor %}
    <!-- 답변 한 개 영역 종료-->

    <div>
      <a href="{% url "board:question_list" %}" class="btn btn-sm btn-primary" id="list">목록으로</a>
    </div>
    
    {% comment %} 답변 등록 {% endcomment %}
    {% comment %} 
    GET : question_detail 을 들어올때는 주소가 http://127.0.0.1:8000/board/1
    POST : answer_create 할때는 주소가 http://127.0.0.1:8000/board/answer/create/2
    GET 이랑 POST 가 서로 주소가 달라서 action= 에다가 POST 주소를 적는다
    {% endcomment %}
    <form action="{% url "board:answer_create" question.id %}" method="post" class="my-3">
      <!-- csrf token-->
      {% csrf_token %}
      <!-- 오류 표시 영역-->
      {% include "form_errors.html" %}
      <div class="form-group mb-3">
        <textarea name="content" id="content" rows="10" class="form-control"></textarea>
      </div>
      <input type="submit" value="답변 등록" class="btn btn-primary" {% if not user.is_authenticated %}disabled="disabled"{% endif %} />
    </form>
  </div>
  <!--목록 클릭 시 이동할 폼 (2024-07-01) 추가-->
  <form action="" method="get" id="actionForm">
    <input type="hidden" name="keyword" value="{{keyword|default_if_none:""}}" id="keyword"/>
    <input type="hidden" name="page" value="{{page}}" id="page"/>
    <input type="hidden" name="so" value="{{so|default_if_none:""}}" id="so"/>
  </form>
{% endblock content %}

{% block script %}
<script src="{% static "js/detail.js" %}"></script>
{% endblock script %}